version: '2'
services:
  db:
    image: postgres:9.4-alpine
    container_name: todo-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
